### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'read'

### ISSUE THREAD

**Issue by gordonj208** [c0decracker/video-splitter#31]
D:\video\main>python ffmpeg-split.py -f video.mp4 -s 10
Traceback (most recent call last):
  File "D:\video\main\ffmpeg-split.py", line 224, in <module>
    main()
  File "D:\video\main\ffmpeg-split.py", line 220, in main
    split_by_seconds(video_length=video_length, **options.__dict__)
  File "D:\video\main\ffmpeg-split.py", line 96, in split_by_seconds
    video_length = get_video_length(filename)
  File "D:\video\main\ffmpeg-split.py", line 77, in get_video_length
    output = subprocess.check_output(("ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\site-packages\run\__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "C:\Python310\lib\site-packages\run\__init__.py", line 121, in create_process
    shlex.split(command),
  File "C:\Python310\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Python310\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Python310\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Python310\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'tuple' object has no attribute 'read'

Is there a fix for this?

**Comment by c0decracker** [comment]
@jgord559 Can you provide an example of command line command you're trying to run please?
